#CREATE DATABASE MVC1_PRACTICE;   
USE MVC1_PRACTICE;


CREATE TABLE MAIN_BOARD(
	BOARD_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
    WRITER 	   VARCHAR(20),
    SUBJECT    VARCHAR(50),
    CONTENT    VARCHAR(1000),
    PASSWD     VARCHAR(20),
    READ_CNT   BIGINT DEFAULT 0,
    ENROLL_DT  TIMESTAMP DEFAULT NOW()
);

CREATE TABLE REPLY_BOARD (
	REPLY_ID   BIGINT AUTO_INCREMENT PRIMARY KEY,
	WRITER 	   VARCHAR(20),
    CONTENT    VARCHAR(200),
    PASSWD     VARCHAR(20),
	ENROLL_DT  TIMESTAMP DEFAULT NOW(),
	BOARD_ID   BIGINT,
	FOREIGN KEY (BOARD_ID) REFERENCES MAIN_BOARD(BOARD_ID)
	ON DELETE CASCADE
);

ALTER TABLE MAIN_BOARD  AUTO_INCREMENT=100000;
ALTER TABLE REPLY_BOARD AUTO_INCREMENT=100000;

